{
    'name': "ShipAny Shipping",
    'description': "Send your parcels through ShipAny and track them online",
    'category': 'Operations/Inventory/Delivery',
    'version': '15.0.1.0.0',
    'depends': ['base', 'stock', 'delivery','website_sale_delivery', 'mail', 'sale'],
    'data': [
        'security/ir.model.access.csv',
        'data/locker_scheduler.xml',
        'views/delivery_carrier_view.xml',
        'views/shipany_carrier_views.xml',
        'views/shipany_service_locations_view.xml',
        'views/stock_picking_view.xml',
        'views/product_view.xml',
        'wizard/delivery_carrier_shipany_view.xml',
        'wizard/choose_delivery_carrier_views_inherit.xml',
        'wizard/shipany_waybill_report.xml',
    ],
    'license': 'OEEL-1',
    'installable': True,
    'application': False,
    'auto_install': False,
    "pre_init_hook": "pre_init_check",
}
