{
  "name"                 :  "Website Loyalty Program",
  "summary"              :  """The module helps to  win your customer loyalty .""",
  "category"             :  "Website",
  "version"              :  "2.1.2",
  "sequence"             :  1,
  "author"               :  "Webkul Software Pvt. Ltd.",
  "license"              :  "Other proprietary",
  "maintainer"           :  "Prakash Kumar",
  "live_test_url"        :  "http://odoodemo.webkul.com/?module=website_loyalty_management",
  "depends"              :  [
                             'website_virtual_product',
                             'wk_wizard_messages',
                             'sale',
                             'portal',
                             'website_sale_management','website_sale_hour','hr_timesheet','purchase','project','account','website_product_options'
                            ],
  "data"                 :  [
                             'security/record_security.xml',
                             'security/ir.model.access.csv',
                             'views/res_config_view.xml',
                             'views/template.xml',
                             'views/website_loyalty_management.xml',
                             'data/data.xml',
                             'views/assets.xml',
                             'views/web_portal_order_form.xml',
                            ],
  "demo"                 :  ['data/demo.xml'],
  "application"          :  True,
  "installable"          :  True,
  "price"                :  69,
  "currency"             :  "USD",
  "pre_init_hook"        :  "pre_init_check",
}
