# -*- coding: utf-8 -*-
{
    'name': 'Website Mask Customization',
    'version': '15.0.1.0.1',
    'sequence': 0,
    'category': 'Website',
    "author": "Socius IGB Pvt.Ltd.",
    "website": "http://www.socius.com",
    'license': 'LGPL-3',
    'support': 'socius@services.com',
    'description':"""
               Website jersey Customization
        """,
    'depends': ['base', 'product', 'sale', 'website_sale', 'sale_management', 'website',
                'point_of_sale', 'auth_oauth'],
    'assets': {
        'web.assets_frontend': [
            'mask_cutomization/static/src/js/mask_preview.js',
            'mask_cutomization/static/src/js/mask_designing.js',
            'mask_cutomization/static/src/ext_lib/three.min.js',
            'mask_cutomization/static/src/ext_lib/GLTFLoader.js',
            'mask_cutomization/static/src/ext_lib/OrbitControls.js',
            'mask_cutomization/static/src/js/home.js',
            'mask_cutomization/static/src/scss/header.css',
            'mask_cutomization/static/src/js/mask_load.js',
            'mask_cutomization/static/src/js/product_packaging.js',
            'mask_cutomization/static/src/js/carton_packaging.js',
            'mask_cutomization/static/src/js/shop_cart.js',
            'mask_cutomization/static/src/js/lotter_player.js',
            'mask_cutomization/static/src/js/image_editor.js',
            'mask_cutomization/static/src/image_editor/scripts/jquery.sweet-modal.min.js',
            'mask_cutomization/static/src/image_editor/messager/jquery.mininoty.js',
            'mask_cutomization/static/src/image_editor/scripts/jquery.SimpleCropper.js',
            'mask_cutomization/static/src/image_editor/scripts/jquery.Jcrop.js',
            'mask_cutomization/static/src/js/shop_checkout.js',
            'mask_cutomization/static/src/js/shop_address.js',
            'mask_cutomization/static/src/js/header.js',
            'mask_cutomization/static/src/image_editor/scripts/canvas-table.js',
            'mask_cutomization/static/src/js/mask_design_load.js',
            'mask_cutomization/static/src/js/sweet.js',
            'mask_cutomization/static/src/js/portal.js',
        ],
        'web.assets_qweb': [
            'mask_cutomization/static/src/xml/template.xml',
        ],
    },
    'data': [
        'security/ir.model.access.csv',
        'data/formbuilder_whitelist.xml',
        'data/mask_public_category.xml',
        'data/mask_product_attribute.xml',
        'data/mask_product_template.xml',
        # reports
        'reports/invoice.xml',
        # website views
        'views/home_page_banner.xml',
        'views/footer.xml',
        'views/header_banner.xml',
        'views/header.xml',
        'views/create_your_mask.xml',
        'views/customize_mask_size.xml',
        'views/website_shop.xml',
        'views/print_area.xml',
        'views/customization_mask_design.xml',
        'views/mask_preview.xml',
        'views/sale_order.xml',
        'views/home.xml',
        'views/login.xml',
        'views/reset_password.xml',
        'views/product_details.xml',
        'views/mask_load.xml',
        'views/product_packaging.xml',
        'views/carton_packaging.xml',
        'views/shop_cart.xml',
        'views/image_editor.xml',
        'views/shop_checkout.xml',
        'views/shop_address.xml',
        'views/mask_design_load.xml',
        'views/shop_confirm.xml',
        'views/about_us.xml',
        'views/contact_us.xml',
        'views/account_invoice.xml',
        'views/portal.xml',
        'views/order_process.xml',
        'views/payment_and_delivery.xml',
        'views/privacy_policy.xml',
        # web views
        'views/web_views/product_attribute_value.xml',
        'views/web_views/res_config.xml',
        'views/web_views/custom_mask_website_sequence.xml',
    ],

    # 'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
